include:
  - project: "apps/nuc-subcharts/gitlab-ci"
    ref: "v1.0.2"
    file:
      - "/variables-subchart.gitlab-ci.yml"

  - project: "apps/nuc-subcharts/gitlab-ci"
    ref: "v1.0.2"
    file:
      - "/test-subchart.gitlab-ci.yml"

  - project: "apps/nuc-subcharts/gitlab-ci"
    ref: "v1.0.2"
    file:
      - "/publish-subchart.gitlab-ci.yml"

stages:
  - lint
  - unit-tests
  - compatibility_tests
  - render
  - validate

  - validate-tag
  - package
  - publish
  - sign
  - verify
