include:
  - project: "apps/nuc-subcharts/gitlab-ci"
    ref: "v1.0.5"
    file:
      - "/variables-subchart.gitlab-ci.yml"

  - project: "apps/nuc-subcharts/gitlab-ci"
    ref: "v1.0.5"
    file:
      - "/test-subchart.gitlab-ci.yml"

  - project: "apps/nuc-subcharts/gitlab-ci"
    ref: "v1.0.5"
    file:
      - "/publish-subchart.gitlab-ci.yml"

  - project: "apps/nuc-subcharts/gitlab-ci"
    ref: "v1.0.5"
    file:
      - "/sign-subchart.gitlab-ci.yml"

stages:
  - lint
  - tests

  - validate-tag
  - package
  - publish

  - sign
  - metadata
  - verify