---
apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: nuc-istio
type: application
version: 1.0.0-rc9
keywords:
  - kubernetes
  - network
  - universal-chart
maintainers:
  - name: Peter Rukin
    email: p.rukin@nixys.ru
  - name: Vyacheslav Vorobev
    email: v.vorobyov@nixys.ru
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - Add Cosign Verification
  artifacthub.io/recommendations: |
    - url: https://nixys.io
  artifacthub.io/signKey: |
    fingerprint: 332FCD67C8B83C68B5AE67884856BB650E18E5427465417E1BC62ED1C417F3BE
    url: https://registry.nixys.io/signkey/cosign.pub

