{{- $tplContext := deepCopy $ -}}
{{- if $.Values.global }}
{{- $_ := set $tplContext "Values" (mergeOverwrite (deepCopy $.Values.global) $.Values) -}}
{{- end }}
{{- range $host, $gateway := .Values.gateways }}
{{- $labels := include "helpers.app.labels" $ | fromYaml | default dict -}}
{{- with $gateway.labels }}
{{- $labels = mergeOverwrite $labels (include "helpers.tplvalues.render" (dict "value" . "context" $tplContext) | fromYaml) -}}
{{- end }}
{{- $annotations := include "helpers.app.genericAnnotations" $ | fromYaml | default dict -}}
{{- with $gateway.annotations }}
{{- $annotations = mergeOverwrite $annotations (include "helpers.tplvalues.render" (dict "value" . "context" $tplContext) | fromYaml) -}}
{{- end }}
---
apiVersion: {{ include "helpers.capabilities.istiogateway.apiVersion" $ }}
kind: Gateway
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" ($gateway.name | default $host) "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- toYaml $labels | nindent 4 }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
spec:
  selector:
    {{- include "helpers.tplvalues.render" (dict "value" $gateway.selector "context" $tplContext) | nindent 4 }}
  servers:
  {{- range $gateway.servers }}
  - hosts:
    {{- range .hosts }}
    - {{ include "helpers.tplvalues.render" (dict "value" . "context" $tplContext) }}
    {{- end }}
    port:
      name: {{ .port.name }}
      number: {{ .port.number }}
      protocol: {{ .port.protocol }}
    {{- with .tls }}
    tls:
    {{- toYaml . | nindent 6 }}
    {{- end }} {{/* end with .tls */}}
  {{- end }}
{{- end -}}
