{{- $tplContext := deepCopy $ -}}
{{- if $.Values.global }}
{{- $_ := set $tplContext "Values" (mergeOverwrite (deepCopy $.Values.global) $.Values) -}}
{{- end }}
{{- range $host, $virtualservice := .Values.virtualservices }}
{{- $labels := include "helpers.app.labels" $ | fromYaml | default dict -}}
{{- with $virtualservice.labels }}
{{- $labels = mergeOverwrite $labels (include "helpers.tplvalues.render" (dict "value" . "context" $tplContext) | fromYaml) -}}
{{- end }}
{{- $annotations := include "helpers.app.genericAnnotations" $ | fromYaml | default dict -}}
{{- with $virtualservice.annotations }}
{{- $annotations = mergeOverwrite $annotations (include "helpers.tplvalues.render" (dict "value" . "context" $tplContext) | fromYaml) -}}
{{- end }}
---
apiVersion: {{ include "helpers.capabilities.istiovirtualservice.apiVersion" $ }}
kind: VirtualService
metadata:
  name: {{ include "helpers.tplvalues.render" (dict "value" ($virtualservice.name | default $host) "context" $tplContext) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- toYaml $labels | nindent 4 }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
spec:
  hosts:
    {{- range $h := $virtualservice.hosts }}
    - {{ include "helpers.tplvalues.render" (dict "value" $h "context" $tplContext) | quote }}
    {{- end }}
  gateways:
    {{- range $virtualservice.gateways }}
    - {{ . | quote }}
    {{- end }}
  http:
    {{- range $httpRoute := $virtualservice.http }}
    - name: {{ $httpRoute.name | default "" | quote }}
      {{- with $httpRoute.match }}
      match:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $httpRoute.route }}
      route:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $httpRoute.retries }}
      retries:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $httpRoute.fault }}
      fault:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $httpRoute.timeout }}
      timeout: {{ . }}
      {{- end }}
      {{- with $httpRoute.rewrite }}
      rewrite:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $httpRoute.corsPolicy }}
      corsPolicy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- if $virtualservice.tls }}
  tls:
    {{- range $virtualservice.tls }}
    - match:
        {{- if .match }}
        {{- toYaml .match | nindent 8 }}
        {{- end }}
      route:
        {{- if .route }}
        {{- toYaml .route | nindent 8 }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if $virtualservice.tcp }}
  tcp:
    {{- range $tcpRoute := $virtualservice.tcp }}
    - {{- toYaml $tcpRoute | nindent 6 }}
    {{- end }}
  {{- end }} {{/* end with $virtualservice.tcp */}}
  {{- with $virtualservice.exportTo }}
  exportTo:
    {{- toYaml . | nindent 4 }}
  {{- end }} {{/* end with $virtualservice.exportTo */}}
{{- end }}

